### ISSUE TITLE
segmentation fault in php-fpm

### ISSUE THREAD

**Issue by stavrak** [goodspb/pdlib#39]
Issue:
When i add the extension into the php.ini, php-fpm is not starting anymore returning segmentation fault.

Background:
After seting the env variable for the pkg config (necessary for me to compile dlib, see https://discuss.getsol.us/d/5423-compiled-library-not-found/2) and installing lang/gcc before running ./configure (otherwise i got a library lstdc++ not found during make) i finally got it compiled.
But if i add it to the php.ini the php-fpm service fails with segmentation fault.

System: 
Nextcloud plugin (12.1-RELEASE-p10) running on trueNas (TrueNAS-12.0-RELEASE) as jail (container).
php version: 7.4.12

**Comment by OliverPA77** [comment]
I have the same issue on TrueNAS-12.0-U1 and PHP 7.4.13, ie. seg fault when starting php. Tried as well in a separate jail without php-fpm - same result.
Frustratingly even with all logging enabled in php.ini there isn't a trace of a log anywhere.

**Comment by rezeptpflichtig** [comment]
hm, I'm stuck at the same point. I will try on a vanilla freebsd system to see if this is related to FreeNAS

**Comment by adeepn** [comment]
freebsd-12.2-p6
truss:
....
munmap(0x801800000,2097152)                      = 0 (0x0)
SIGNAL 11 (SIGSEGV) code=SEGV_MAPERR trapno=12 addr=0x804d255f0
process killed, signal = 11 (core dumped)

And gdb:
(gdb) bt full
#0  0x0000000804d255f0 in ?? ()
No symbol table info available.
#1  0x0000000800e65491 in __cxa_finalize () from /lib/libc.so.7
No symbol table info available.
#2  0x0000000800df7ed1 in exit () from /lib/libc.so.7
No symbol table info available.
#3  0x000000000099c189 in main (argc=1, argv=0x7fffffffebe0) at sapi/cli/php_cli.c:1397
        c = -1
        exit_status = 0
        module_started = 1
        sapi_started = 1
        php_optarg = 0x0
        php_optind = 1
        use_extended_info = 0
        ini_path_override = 0x0
        ini_entries = 0x80117e000 "html_errors=0\nregister_argc_argv=1\nimplicit_flush=1\noutput_buffering=0\nmax_execution_time=0\nmax_input_time=-1\n"
        ini_entries_len = 110
        ini_ignore = 0
        sapi_module = 0xa2c240 <cli_sapi_module>

**Comment by EthanHindmarsh** [comment]
Hello, I am having the same issue on a vanilla FreeBSD system ( FreeBSD 13.0-RELEASE-p4 )

**Comment by SebastianChudoba** [comment]
`Performing sanity check on php-fpm configuration:
Segmentation fault`

no way of getting pdlib running on freebsd with php8

**Comment by jasonhensler** [comment]
Clean build on freebsd 13.1 with php8.0.19, dlib install from ports or from okg still showing segmentation fault for php-fpm.

**Comment by SebastianChudoba** [comment]
Still seg faults when building on freebsd. It's building fine but starting php-fpm with the extension seg faults.
Using pkg dlib-cpp-19.22, php80

make test results in *** Error code 139

**Comment by Lexden12** [comment]
> Still seg faults when building on freebsd. It's building fine but starting php-fpm with the extension seg faults. Using pkg dlib-cpp-19.22, php80
> 
> make test results in *** Error code 139

I just ran into this issue today as well on TrueNAS-13.0-U2. Hoping there might be a fix sometime so I can get FaceRecognition installed.

**Comment by brennoflavio** [comment]
Could reproduce this error in freebsd with php 7.4 too

**Comment by christianguenter1** [comment]
dito on php 8.2.17

**Comment by kevans91** [comment]
Will be fixed in FreeBSD 14.3, may issue an EN for FreeBSD 14.2, 13.5

**Comment by chris-x-tra** [comment]
Please make an Errata Notice fro FreeBSD 14.2.

**Comment by chris-x-tra** [comment]
I updated to FreeBSD 8.4-BETA1 today, and it works. :)
